const responseCodes = {
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR" as "INTERNAL_SERVER_ERROR",
    CLIENT_ERROR: "CLIENT_ERROR" as "CLIENT_ERROR",
    MISSING_PARAM_ERROR: "MISSING_PARAM_ERROR" as "MISSING_PARAM_ERROR",
    INVALID_PARAM_ERROR: "INVALID_PARAM_ERROR" as "INVALID_PARAM_ERROR",
    WRONG_CERT_PASSWORD: "WRONG_CERT_PASSWORD" as "WRONG_CERT_PASSWORD",
    CERTIFICATE_NOT_FOUND: "CERTIFICATE_NOT_FOUND" as "CERTIFICATE_NOT_FOUND",
    CERT_VALID: "CERT_VALID" as "CERT_VALID",
    EXPIRED_TOKEN: "EXPIRED_TOKEN" as "EXPIRED_TOKEN",
    TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND" as "TOKEN_NOT_FOUND",
};

export default responseCodes;
export { responseCodes };
